title: Jiachao&enspPeng's Homepage
page-top-title: Jiachao&enspPeng
top-section-bg-text: Be what you wanna be
home-subtitle: Jiachao&enspPeng;|&ensp;彭甲超
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
