title: Jiachao Peng's Homepage
page-top-title: Jiachao Peng
top-section-bg-text: Be what you wanna be
home-subtitle: Jiachao Peng &ensp;|&ensp;彭甲超
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
